'use strict';
const $=s=>document.querySelector(s),KEY='qianli-culture-v2';
let store={version:2,current:null,records:[],bookmarks:[],read:[],answers:{},posts:[],replies:{},liked:[],draft:{title:'',body:'',tag:'家乡记忆'},sound:false},storageOK=true,busy=false,filter='全部',quizIndex=0;
try{const data=JSON.parse(localStorage.getItem(KEY));if(data?.version===2){for(const key of ['records','bookmarks','read','posts','liked'])if(Array.isArray(data[key]))store[key]=data[key];for(const key of ['answers','replies','draft'])if(data[key]&&typeof data[key]==='object'&&!Array.isArray(data[key]))store[key]=data[key];if(data.current&&Culture.validLines(data.current.lines))store.current=data.current;store.sound=!!data.sound;if(typeof data.chatDraft==='string')store.chatDraft=data.chatDraft.slice(0,1000);}}catch{storageOK=false;}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function categoryLabel(tag){return tag;}
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';window.MotionUI?.toast();clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',3000);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(store));storageOK=true;return true;}catch{storageOK=false;toast('当前无法保存到浏览器，请导出备份。');return false;}}
function route(){return (location.hash.slice(1)||'splash').split('/');}
function go(path){if(location.hash==='#'+path){render();window.scrollTo(0,0);}else location.hash=path;}
function redraw(){save();render();}
function focusHeading(){window.scrollTo(0,0);const h=$('#app h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}}
let audio;
function chime(){if(!store.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();[523.25,659.25,783.99].forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+i*.07;o.frequency.value=f;g.gain.setValueAtTime(.001,t);g.gain.linearRampToValueAtTime(.03,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+.3);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.35);});}catch{}}
function soundUI(){const b=$('#sound');b.setAttribute('aria-pressed',String(store.sound));b.setAttribute('aria-label',store.sound?'关闭声音':'开启声音');b.textContent=store.sound?'♫':'♪';}
$('#sound').onclick=()=>{store.sound=!store.sound;save();soundUI();chime();};soundUI();
function landscape(){return `<div class="art culture-art" role="img" aria-label="层叠青绿山水间的铜钱、河流与亭阁，无人物"><svg viewBox="0 0 400 340" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><defs><pattern id="grain" width="8" height="8" patternUnits="userSpaceOnUse"><circle cx="2" cy="3" r=".6" fill="#F4EDDE" opacity=".16"/></pattern></defs><rect width="400" height="340" fill="#EAE0C9"/><circle cx="285" cy="68" r="46" fill="#C89B5A"/><path d="M0 255L70 83l45 88L176 53l70 155L305 120l95 122v98H0" fill="#2C6A7E"/><path d="M0 273l94-113 78 110 59-127 82 115 87-58v140H0" fill="#5A9778"/><path d="M0 307q104-70 190-8t210-14v55H0" fill="#1F4E5F"/><path d="M208 340q72-24 34-47t25-30" stroke="#C89B5A" stroke-width="13" fill="none"/><g transform="translate(145 105) rotate(-12 55 55)"><circle cx="60" cy="67" r="59" fill="#A97C3F"/><circle cx="55" cy="58" r="59" fill="#C89B5A"/><circle cx="55" cy="58" r="49" fill="none" stroke="#F4EDDE" stroke-width="2"/><path d="M39 42h32v32H39z" fill="#1F4E5F"/><path d="M47 20h16m-8-8v16m-37 27h12m51 0h12M47 95h16" stroke="#1F4E5F" stroke-width="4"/></g><path d="M60 275v-34h36v34M48 241q33-12 31-23 5 11 29 23" fill="#1F4E5F"/><path d="M68 249h8v26h-8m12-26h8v26h-8" fill="#C89B5A"/><path d="M15 57q13-17 25-4 12-28 29-7 14-8 22 10" fill="none" stroke="#F4EDDE" stroke-width="9"/><rect width="400" height="340" fill="url(#grain)"/></svg><span class="art-label">山河入卦 · 文脉有续</span><span class="chapter-mark">千里铜钱 / 文化在日常延续</span></div>`;}
function home(){return `<div class="hero"><div class="hero-copy"><p class="eyebrow">文化传承 · 知识普及 · 社区共话</p><h1>掷一枚铜钱，<br>读一段文化。</h1><p class="hero-desc">从阴阳爻到古籍，从家乡记忆到彼此交流。<br>让文化被理解，也被继续讲述。</p><button class="primary" data-action="start">${store.current?'继续铜钱体验':'开启铜钱体验'} ↗</button><p class="micro">六次投掷 · 认识卦象 · 留下自己的理解</p></div>${landscape()}</div><div class="feature-row"><a class="feature" href="#library"><b>01 &nbsp; 读懂文化</b><span>入门导读与有出处的原文</span></a><a class="feature" href="#quiz"><b>02 &nbsp; 学有所获</b><span>用小测验巩固一个知识点</span></a><a class="feature" href="#community"><b>03 &nbsp; 一起延续</b><span>记录习俗，交流不同理解</span></a></div><div class="section-head"><h2>从这里，走近传统</h2><a href="#library" class="micro">全部导读 →</a></div><div class="chapter-list">${LESSONS.map((l,i)=>`<a href="#lesson/${l.id}" class="chapter-item"><span>${l.symbol}</span><div><b>${l.title}</b><small>${l.tag}</small></div></a>`).join('')}</div><div class="purpose"><span class="badge">可持续的文化生活</span><p>学会一点，记录一点，再与别人分享一点。这里关注文化知识的持续学习、记忆的保存，以及代际与地域之间的交流。</p><a href="#community" class="text-link">参与文化共话 →</a></div>`;}
function yao(lines){const names={6:'老阴',7:'少阳',8:'少阴',9:'老阳'};return `<div class="yao-board"><div class="yao" role="img" aria-label="${lines.length?lines.map((n,i)=>`第${i+1}爻${names[n]}`).join('，'):'六爻尚未生成'}">${Array.from({length:6},(_,i)=>`<div class="yao-row ${lines[i]?'':'empty'} ${[6,9].includes(lines[i])?'changing':''}"><i></i>${[6,8].includes(lines[i])?'<i></i>':''}</div>`).join('')}</div><p class="micro center">初爻在下，自下而上 · 朱砂色为动爻</p></div>`;}
function play(){const s=store.current;if(!s)return `<div class="screen"><h1>从一次投掷，<br>认识一条爻。</h1><button class="primary wide" data-action="start">开启铜钱体验 ↗</button></div>`;if(s.lines.length===6)return result(s);return `<div class="screen"><a class="back" href="#home">← 返回体验首页</a><p class="eyebrow">铜钱起意 · 文化体验</p><h1>让铜钱落定，<br>看六爻成形。</h1><p>三枚铜钱，六次投掷。在互动中认识阴阳爻，读懂卦象的组成。</p><div class="coin-stage"><span class="coin"></span><span class="coin"></span><span class="coin"></span></div>${yao(s.lines)}<p class="center" aria-live="polite">已完成 ${s.lines.length} / 6 次</p><button class="primary wide" data-action="toss" ${busy?'disabled':''}>投掷第 ${s.lines.length+1} 次</button><div class="center"><button class="text-button" data-action="quick" ${busy?'disabled':''}>快速生成剩余爻</button></div><details><summary>这段体验怎样运作？</summary><p>每枚虚拟铜钱等概率取 2 或 3，三枚相加生成 6、7、8、9 四种爻值。6 与 9 为动爻。本网页使用程序随机模拟，供了解文化符号，不据此预测现实运势。</p></details></div>`;}
function result(s){const r=Culture.decode(s.lines,HEXAGRAMS);return `<div class="screen"><a class="back" href="#home">← 返回体验首页</a><p class="eyebrow">六爻已成 · 从符号读起</p><h1>${esc(r.hex.name)}</h1><div class="hex-result"><span class="hex-symbol">${r.hex.symbol}</span><div><p>上卦：${r.upper.symbol} ${r.upper.name} · ${r.upper.nature}</p><p>下卦：${r.lower.symbol} ${r.lower.name} · ${r.lower.nature}</p></div></div>${yao(s.lines)}<div class="lens"><span class="badge">古籍原文 · 卦辞</span><p class="quote">${esc(r.hex.judgment)}</p><p class="micro">《周易》${esc(r.hex.name)}卦。经文沿用原项目整理，标点为现代形式。</p><a href="https://ctext.org/book-of-changes/yi-jing/zhs" target="_blank" rel="noopener" class="text-link">前往《周易》目录核对原文 ↗</a></div><h2>先认识结构，再继续阅读</h2><p>这个卦由下方的“${r.lower.name}”与上方的“${r.upper.name}”组成，可以从“${r.lower.nature}”与“${r.upper.nature}”两个自然意象入手观察。</p><p>${r.moving.length?`第 ${r.moving.join('、')} 爻为动爻；将它们阴阳互换后，对应“${r.changed.name}”。`:'本次没有动爻，阴阳结构不发生变化。'}</p><p class="micro">以上为符号结构说明，不是对个人生活的吉凶判断。</p><a class="secondary wide" href="#lesson/symbols">读一读：从一条爻，读懂八卦 →</a><details><summary>展开六条爻辞</summary>${r.hex.lines.map(line=>`<p>${esc(line)}</p>`).join('')}</details>${Journey.checkpoint(s)}<label for="note">你注意到了什么？有什么想继续了解？</label><textarea id="note" maxlength="1000" placeholder="记下一个发现或一个问题……">${esc(s.note)}</textarea><p class="micro">这段笔记仅保存在本机，不会自动发布到共话。</p><button class="primary wide" data-action="save-result">保存到我的足迹 ↗</button></div>`;}
function library(){return `<div class="screen"><p class="eyebrow">藏书 · 从认识到理解</p><h1>读得懂，<br>才传得下去。</h1><p>原文有出处，解读有边界。把小知识慢慢积成自己的文化地图。</p><a class="primary wide" href="#quiz">知识小测 · 四题入门 ↗</a><div class="book-grid">${LESSONS.map(l=>`<article class="book-card"><span class="library-symbol">${l.symbol}</span><p class="micro">${l.tag} ${store.read.includes(l.id)?'· 已读':''}</p><h2>${l.title}</h2><p>${l.intro}</p><div class="actions"><a class="secondary" href="#lesson/${l.id}">开始阅读 →</a><button class="bookmark" data-bookmark="${l.id}" aria-pressed="${store.bookmarks.includes(l.id)}">${store.bookmarks.includes(l.id)?'★ 已收藏':'☆ 收藏'}</button></div></article>`).join('')}</div><div class="purpose"><p class="micro">经文与现代导读分别标注。页面中的习俗记录方法为本作编写，不冒充古籍内容。</p></div></div>`;}
function lesson(id){const l=LESSONS.find(x=>x.id===id);if(!l)return missing();return `<article class="screen"><a class="back" href="#library">← 返回藏书</a><p class="eyebrow">${l.tag}</p><h1>${l.title}</h1><p class="muted">${l.intro}</p>${id==='symbols'?Journey.resume():''}${l.quote?`<div class="lens"><span class="badge">古籍原文</span><p class="quote">${l.quote}</p><p class="micro">${l.source}</p><a href="${l.url}" target="_blank" rel="noopener" class="text-link">核对原文 ↗</a></div>`:''}<p class="micro">${l.quote?'以下为本作编写的入门导读':'本作原创：社区记录与交流建议'}</p>${l.paragraphs.map(p=>`<p>${p}</p>`).join('')}${id==='symbols'?`<div class="trigram-grid">${Object.values(Culture.trigrams).map(t=>`<div><span>${t.symbol}</span><b>${t.name}</b><small>${t.nature}</small></div>`).join('')}</div>`:''}<div class="purpose"><h2>留一个问题，一起聊聊</h2><p>${l.question}</p><button class="secondary" data-discuss="${l.id}">带着这个问题去共话 →</button></div><div class="actions"><button class="primary" data-read="${id}">${store.read.includes(id)?'✓ 已完成阅读':'标记已读'}</button><button class="secondary" data-bookmark="${id}" aria-pressed="${store.bookmarks.includes(id)}">${store.bookmarks.includes(id)?'★ 已收藏':'☆ 收藏这篇'}</button></div><a class="text-button" href="#quiz">试试知识小测 →</a></article>`;}
function quiz(){const q=QUIZ[quizIndex],selected=store.answers[quizIndex],answered=Number.isInteger(selected),count=Object.keys(store.answers).filter(k=>Number.isInteger(store.answers[k])).length,correct=QUIZ.filter((q,i)=>store.answers[i]===q.answer).length;return `<div class="screen"><a class="back" href="#library">← 返回藏书</a><p class="eyebrow">知识小测 · ${quizIndex+1} / ${QUIZ.length}</p><h1>记住一点，<br>理解多一点。</h1><h2>${q.question}</h2>${q.options.map((o,i)=>`<button class="choice ${answered&&i===q.answer?'correct':''}" data-answer="${i}" ${answered?'disabled':''}>${String.fromCharCode(65+i)} · ${o}${answered&&selected===i?'（你的选择）':''}${answered&&i===q.answer?' ✓':''}</button>`).join('')}${answered?`<div class="lens" role="status"><b>${selected===q.answer?'答对了':'一起再看一下'}</b><p>${q.explanation}</p><a class="text-link" href="#lesson/${q.lesson}">回到相关导读 →</a></div>`:''}<div class="actions"><button class="secondary" data-action="quiz-prev" ${quizIndex===0?'disabled':''}>上一题</button><button class="primary" data-action="quiz-next" ${quizIndex===QUIZ.length-1?'disabled':''}>下一题</button></div><p class="micro">已回答 ${count} / ${QUIZ.length} 题 · 答对 ${correct} 题</p>${count===QUIZ.length?'<button class="text-button" data-action="quiz-reset">重新练习</button>':''}</div>`;}
function community(){const own=store.posts.filter(p=>filter==='全部'||p.tag===filter),topics=TOPICS.filter(p=>filter==='全部'||p.tag===filter);return `<div class="screen"><p class="eyebrow">社区共话 · 文化在交流中延续</p><h1>你的记忆，<br>也是文化的一页。</h1><p>聊家乡习俗，共读一段古文，或把一个问题交给讨论。</p><div class="notice">本地体验版：主题由本站提供，发帖与回复仅保存在这台设备，不会发送给其他人。接入服务端后才能进行真实跨用户交流。</div><a class="primary wide" href="#compose" style="margin-top:20px">写下我的文化分享 ＋</a><div class="filters" aria-label="话题筛选">${['全部','家乡记忆','经典共读','知识问答'].map(t=>`<button data-filter="${t}" aria-pressed="${filter===t}" class="${filter===t?'selected':''}">${categoryLabel(t)}</button>`).join('')}</div>${own.map(p=>postCard(p,false)).join('')}${topics.map(p=>postCard(p,true)).join('')}${!own.length?'<p class="micro">这个话题下还没有你的分享，可以先从上面的讨论题开始。</p>':''}</div>`;}
function postCard(p,topic){return `<a class="post-card" href="#thread/${p.id}"><span class="badge">${categoryLabel(p.tag)}</span><span class="micro"> ${topic?'本站讨论题':'我的分享 · 仅本机'}</span><h2>${esc(p.title)}</h2><p>${esc(p.body.slice(0,105))}${p.body.length>105?'…':''}</p><span class="micro">${(store.replies[p.id]||[]).length} 条本地回复 · 进入交流 →</span></a>`;}
function compose(){return `<div class="screen"><a class="back" href="#community">← 返回共话</a><p class="eyebrow">我的文化分享</p><h1>从一段记忆，<br>开启一场交流。</h1><p class="micro">写明个人经历与资料出处；讲述他人的故事前，请先征得同意。</p><form id="post-form"><label for="post-tag">话题</label><select id="post-tag">${['家乡记忆','经典共读','知识问答'].map(t=>`<option value="${t}" ${store.draft.tag===t?'selected':''}>${categoryLabel(t)}</option>`).join('')}</select><label for="post-title">标题（最多 60 字）</label><input id="post-title" required maxlength="60" value="${esc(store.draft.title)}" placeholder="例如：我家怎样过中秋"><label for="post-body">内容（最多 1000 字）</label><textarea id="post-body" required maxlength="1000" rows="7" placeholder="发生在哪里？谁告诉你的？你还有什么想问的？">${esc(store.draft.body)}</textarea><p class="micro">草稿自动保存在本机。保存后可在共话中查看和添加本地回复。</p><button class="primary wide" type="submit">保存分享 · 仅本机</button></form></div>`;}
function thread(id){const p=TOPICS.find(x=>x.id===id)||store.posts.find(x=>x.id===id);if(!p)return missing();const topic=TOPICS.some(x=>x.id===id);return `<div class="screen"><a class="back" href="#community">← 返回共话</a><p class="eyebrow">${categoryLabel(p.tag)} · ${topic?'本站讨论题':'我的分享 · 仅本机'}</p><h1>${esc(p.title)}</h1><p class="user-text">${esc(p.body)}</p><button class="secondary" data-like="${id}" aria-pressed="${store.liked.includes(id)}">${store.liked.includes(id)?'♥ 已收藏话题':'♡ 收藏话题'}</button><div class="section-head"><h2>本地回复 · ${(store.replies[id]||[]).length}</h2></div>${(store.replies[id]||[]).map(r=>`<article class="reply"><b>我 · 仅本机</b><p class="user-text">${esc(r.body)}</p><small>${new Date(r.date).toLocaleDateString('zh-CN')}</small></article>`).join('')||'<p class="muted">还没有本地回复，写下你的第一段想法。</p>'}<form id="reply-form" data-thread="${id}"><label for="reply-body">补充一段记忆，或提出一个问题</label><textarea id="reply-body" required maxlength="1000" placeholder="尊重差异，注明来源，让讨论有据可循。"></textarea><p class="micro">仅在这台设备保存，其他人不会收到这条回复。</p><button class="primary wide" type="submit">保存回复 · 仅本机</button></form></div>`;}
function journal(){return `<div class="screen"><p class="eyebrow">我的足迹 · 本地保存</p><h1>学过的知识，<br>留下的理解。</h1><div class="stats"><span>已读 <strong>${store.read.length}</strong> 篇</span><span>收藏 <strong>${store.bookmarks.length}</strong> 篇</span><span>文化体验 <strong>${store.records.length}</strong> 次</span></div><button class="secondary" data-action="export">导出我的文化足迹 ↓</button><div class="section-head"><h2>收藏的导读</h2></div>${LESSONS.filter(l=>store.bookmarks.includes(l.id)).map(l=>`<a class="post-card" href="#lesson/${l.id}"><h2>${l.title} →</h2></a>`).join('')||'<p class="muted">还没有收藏，去藏书遇见第一篇导读。</p>'}<div class="section-head"><h2>收藏的共话</h2></div>${[...TOPICS,...store.posts].filter(p=>store.liked.includes(p.id)).map(p=>`<a class="post-card" href="#thread/${p.id}"><h2>${esc(p.title)} →</h2></a>`).join('')||'<p class="micro">在话题里点击收藏，就能在这里再次找到它。</p>'}<div class="section-head"><h2>铜钱体验记录</h2></div>${[...store.records].reverse().map(s=>{const r=Culture.decode(s.lines,HEXAGRAMS);return `<article class="record"><span class="micro">${new Date(s.date).toLocaleDateString('zh-CN')}</span><h2>${r.hex.symbol} ${r.hex.name}</h2><p class="user-text">${esc(s.note)||'这次还没有笔记。'}</p><a href="#record/${s.id}" class="text-link">回看六爻与原文 →</a></article>`;}).join('')||'<p class="muted">完成铜钱体验并保存后，你的笔记会出现在这里。</p>'}<div class="purpose"><a href="#community">查看我的文化分享 →</a><p class="micro">共 ${store.posts.length} 篇本地分享。数据不自动同步到其他设备，清除网站数据前请导出。</p></div></div>`;}
function record(id){const s=store.records.find(x=>x.id===id);if(!s)return missing();const r=Culture.decode(s.lines,HEXAGRAMS);return `<div class="screen"><a class="back" href="#journal">← 返回足迹</a><p class="eyebrow">文化体验回看</p><h1>${r.hex.name}</h1>${yao(s.lines)}<p>上卦 ${r.upper.name} · ${r.upper.nature} / 下卦 ${r.lower.name} · ${r.lower.nature}</p><div class="lens"><span class="badge">卦辞原文</span><p>${esc(r.hex.judgment)}</p></div><h2>当时的理解</h2><p class="user-text">${esc(s.note)||'没有留下笔记。'}</p><a class="secondary" href="#lesson/symbols">继续学习 →</a>${Journey.followup()}</div>`;}
function settings(){return `<div class="screen"><a class="back" href="#home">← 返回体验首页</a><p class="eyebrow">偏好设置</p><h1>设置</h1><section class="purpose"><h2>界面语言</h2><p>首次打开默认使用英文。你的语言选择会保存在这台设备上。</p><div class="language-options" role="group" aria-label="界面语言"><button class="choice" data-language="en" lang="en" aria-pressed="${window.APP_LANGUAGE==='en'}">English <span>${window.APP_LANGUAGE==='en'?'✓':''}</span></button><button class="choice" data-language="zh-CN" lang="zh-CN" aria-pressed="${window.APP_LANGUAGE==='zh-CN'}">简体中文 <span>${window.APP_LANGUAGE==='zh-CN'?'✓':''}</span></button></div><p class="micro">切换语言不会改动你的笔记、分享或学习记录。</p></section><a class="secondary" href="#journal">查看我的足迹 →</a></div>`;}
function missing(){return '<div class="screen"><h1>这一页还没有内容</h1><a class="primary" href="#home">回到首页</a></div>';}
function render(){window.MotionUI?.before();const [page,id]=route();const views={splash:Studio.splash,home:Studio.welcome,learn:Journey.intro,map:Studio.map,chat:Studio.chat,place:()=>Studio.place(id),explore:home,settings,play:Studio.play,library:Studio.library,lesson:()=>lesson(id),quiz,community,compose,thread:()=>thread(id),journal,record:()=>record(id)};$('#app').innerHTML=(!storageOK?'<p class="notice">浏览器存储不可用，当前内容只暂存在内存。请及时导出。</p>':'')+(views[page]||Studio.welcome)();const nav=['lesson','quiz'].includes(page)?'library':['compose','thread'].includes(page)?'community':page==='record'?'journal':page==='play'?'home':page;document.querySelectorAll('nav a').forEach(a=>{const on=a.dataset.tab===nav;a.classList.toggle('active',on);if(on)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});Studio.mount(views[page]?page:'home');window.MotionUI?.after(page);}
async function toss(quick){if(busy||!store.current||store.current.lines.length>=6)return;busy=true;const s=store.current;$('.coin-stage')?.classList.add('tossing');document.querySelectorAll('[data-action="toss"],[data-action="quick"]').forEach(b=>b.disabled=true);chime();await new Promise(r=>setTimeout(r,matchMedia('(prefers-reduced-motion: reduce)').matches?10:650));s.lines.push(Culture.toss());if(quick)while(s.lines.length<6)s.lines.push(Culture.toss());busy=false;save();if(route()[0]==='play'){render();if(s.lines.length===6)focusHeading();}}
$('#app').addEventListener('input',e=>{const {id,value}=e.target;if(id==='note'&&store.current)store.current.note=value;if(id==='post-title')store.draft.title=value;if(id==='post-body')store.draft.body=value;if(id==='post-tag')store.draft.tag=value;if(['note','post-title','post-body','post-tag'].includes(id))save();});
$('#app').addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='post-form'){const title=$('#post-title').value.trim(),body=$('#post-body').value.trim(),tag=$('#post-tag').value,error=Culture.validatePost(title,body);if(error){toast(error);return;}const id='post-'+Culture.fresh().id;store.posts.push({id,title,body,tag,date:new Date().toISOString()});store.draft={title:'',body:'',tag:'家乡记忆'};const ok=save();go('thread/'+id);toast(ok?'分享已保存到本机。':'暂存在内存，请导出备份。');}else if(e.target.id==='reply-form'){const body=$('#reply-body').value.trim(),id=e.target.dataset.thread;if(!body||body.length>1000){toast('请输入 1–1000 字的回复。');return;}store.replies[id]??=[];store.replies[id].push({body,date:new Date().toISOString()});const ok=save();render();toast(ok?'回复已保存到本机。':'暂存在内存，请导出备份。');}});
$('#app').addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;
if(b.dataset.language){window.setLanguage(b.dataset.language);return;}
if(b.dataset.bookmark){const id=b.dataset.bookmark;store.bookmarks=store.bookmarks.includes(id)?store.bookmarks.filter(x=>x!==id):[...store.bookmarks,id];redraw();return;}
if(b.dataset.read){if(!store.read.includes(b.dataset.read))store.read.push(b.dataset.read);redraw();toast('已记入阅读足迹。');return;}
if(b.dataset.discuss){const l=LESSONS.find(l=>l.id===b.dataset.discuss);if(!store.draft.title&&!store.draft.body)store.draft={title:l.question,body:`阅读《${l.title}》后的想法：\n`,tag:l.id==='sharing'?'家乡记忆':'经典共读'};save();go('compose');return;}
if(b.dataset.filter){filter=b.dataset.filter;render();return;}
if(b.dataset.like){const id=b.dataset.like;store.liked=store.liked.includes(id)?store.liked.filter(x=>x!==id):[...store.liked,id];redraw();return;}
if(b.dataset.answer!==undefined){if(!Number.isInteger(store.answers[quizIndex]))store.answers[quizIndex]=Number(b.dataset.answer);redraw();return;}
switch(b.dataset.action){case'start':go(store.current?'play':'learn');break;case'toss':toss(false);break;case'quick':toss(true);break;case'save-result':if(store.current?.lines.length===6){store.records.push({...store.current,date:new Date().toISOString()});store.current=null;const ok=save();go('journal');toast(ok?'已保存到文化足迹。':'暂存在内存，请导出备份。');}break;case'quiz-prev':quizIndex=Math.max(0,quizIndex-1);render();focusHeading();break;case'quiz-next':quizIndex=Math.min(QUIZ.length-1,quizIndex+1);render();focusHeading();break;case'quiz-reset':store.answers={};quizIndex=0;redraw();focusHeading();break;case'export':{const blob=new Blob([JSON.stringify({...store,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='千里铜钱-文化足迹.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);break;}}
});
window.addEventListener('hashchange',()=>{render();focusHeading();});render();
