/* A short, bilingual learning loop. No account or prediction is implied. */
window.Journey = (() => {
  const t=(en,zh)=>window.APP_LANGUAGE==='zh-CN'?zh:en;
  function intro(){return `<section class="screen journey"><a class="back" href="#home">← ${t('Welcome','欢迎页')}</a><p class="eyebrow">${t('LEARN · TRY · REFLECT','认识 · 体验 · 记录')}</p><h1>${t('A symbol you can understand.','从一个符号，开始理解。')}</h1><p>${t('About 3 minutes. Discover how six lines form a traditional symbol, then keep one observation.','约三分钟。认识六条爻怎样组成传统符号，再留下一个发现。')}</p><div class="purpose"><h2>${t('Two kinds of line','两种爻')}</h2><p><strong>━━━━</strong> ${t('Yang · one unbroken line','阳爻 · 连续的一条线')}</p><p><strong>━━ ━━</strong> ${t('Yin · a line with a gap','阴爻 · 中间断开的线')}</p></div><p>${t('Three virtual coins make one line. Cast six times; the first line sits at the bottom.','三枚虚拟铜钱生成一条爻。投掷六次，第一条在最下面。')}</p><p class="notice">${t('This is a cultural learning activity. Random results do not predict your future.','这是文化学习体验。随机结果不预测你的未来。')}</p><button class="primary wide" data-journey="begin">${t('Try the six lines','开始认识六爻')} →</button><a class="text-button" href="#lesson/symbols">${t('Read the guide first','先读入门导读')}</a></section>`;}
  function checkpoint(s){const answered=['yin','yang'].includes(s.learningAnswer);return `<section class="purpose journey-check"><h2>${t('What did you discover?','你发现了什么？')}</h2><p>${t('Which line has a gap in the middle?','哪一种爻的中间是断开的？')}</p><div class="actions">${['yin','yang'].map(a=>`<button class="secondary" data-journey-answer="${a}" aria-pressed="${s.learningAnswer===a}">${a==='yin'?t('Yin','阴爻'):t('Yang','阳爻')}</button>`).join('')}</div>${answered?`<p role="status">${s.learningAnswer==='yin'?t('Exactly. Yin is broken; yang is unbroken.','是的。阴爻中断，阳爻连续。'):t('Look at the gap: that is yin. Yang is unbroken. You can try again.','再看一下中间的空隙：这是阴爻，阳爻是连续的。你可以再试一次。')}</p>`:''}<p>${t('In your note below, describe one thing you noticed and one question you still have. You can revisit it in Journal.','在下方笔记中，写一个发现和一个仍想了解的问题。保存后可在“足迹”回看。')}</p></section>`;}
  document.getElementById('app').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.journey==='begin'){store.current??=Culture.fresh();save();go('play');}if(b.dataset.journeyAnswer&&store.current){store.current.learningAnswer=b.dataset.journeyAnswer;save();render();document.querySelector('.journey-check')?.scrollIntoView({block:'nearest'});}});
  function followup(){return `<section class="purpose"><h2>${t('Carry it into everyday life','让文化回到日常')}</h2><p>${t('Ask someone about a local custom. With their permission, record where it is practised, who described it, and what is different in your own experience.','问一位熟悉的人：家乡有什么习俗？征得同意后，记录地点、讲述者，以及与你经历不同的地方。')}</p><a class="secondary wide" href="#compose">${t('Write a cultural memory','记录一段文化记忆')} →</a><p class="micro">${t('Saved on this device. This prototype does not publish to a live community.','仅保存在本机。此原型不会发布到在线社区。')}</p></section>`;}
  function resume(){return store.current?`<a class="primary wide" href="#play">${t('Return to your coin experience','返回正在进行的铜钱体验')} →</a>`:`<a class="primary wide" href="#learn">${t('Try what you learned','试试刚学到的知识')} →</a>`;}
  return {intro,checkpoint,followup,resume};
})();
