// Generated by scripts/build-locales.py
/* Culture experience: transparent coin simulation; no material-consumption game. */
(function(root){
const trigrams={
'111':{name:'Qian',symbol:'☰',nature:'Heaven'},'000':{name:'Kun',symbol:'☷',nature:'Earth'},
'100':{name:'Zhen',symbol:'☳',nature:'Thunder'},'011':{name:'Xun',symbol:'☴',nature:'Wind'},
'010':{name:'Kan',symbol:'☵',nature:'Water'},'101':{name:'Li',symbol:'☲',nature:'Fire'},
'001':{name:'Gen',symbol:'☶',nature:'Mountain'},'110':{name:'Dui',symbol:'☱',nature:'Lake'}
};
function toss(random=Math.random){return Array.from({length:3},()=>random()<.5?2:3).reduce((a,b)=>a+b,0);}
function validLines(lines,complete=false){return Array.isArray(lines)&&lines.length<=(6)&&(!complete||lines.length===6)&&lines.every(n=>[6,7,8,9].includes(n));}
function image(lines,changed=false){if(!validLines(lines,true))throw Error('Six complete lines are required');return lines.map(n=>changed&&[6,9].includes(n)?(n===6?'1':'0'):([7,9].includes(n)?'1':'0')).join('');}
function decode(lines,hexagrams){const bits=image(lines),changed=image(lines,true);return {hex:hexagrams.find(h=>h.image===bits),changed:hexagrams.find(h=>h.image===changed),lower:trigrams[bits.slice(0,3)],upper:trigrams[bits.slice(3)],moving:lines.flatMap((n,i)=>[6,9].includes(n)?[i+1]:[])};}
function fresh(){return {id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8),lines:[],note:''};}
function validatePost(title,body){if(!title.trim()||!body.trim())return 'Please enter a title and story.';if(title.trim().length>60||body.trim().length>1000)return 'Use up to 60 characters for the title and 1,000 for the story.';return '';}
const api={trigrams,toss,validLines,image,decode,fresh,validatePost};root.Culture=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
