/* English language pack. Source excerpts are editorial renderings, not attributed translations. */
const LESSONS=[
{id:'symbols',tag:'Basics · 2 min',title:'Meet the eight trigrams',symbol:'☰',intro:'Start with the symbols. A small observation can open a door to cultural knowledge.',quote:'Qian represents heaven; Kun represents earth.',source:'Editorial English rendering of an excerpt from the Shuogua commentary',url:'https://ctext.org/book-of-changes/shuo-gua',paragraphs:['A yang line is unbroken; a yin line has a gap in the middle. Three lines form one of eight trigrams. Two trigrams stacked together form a six-line hexagram.','Traditionally, lines are counted from bottom to top. In this experience, each cast produces one line. Six casts make a complete hexagram.','Heaven, earth, thunder, wind, water, fire, mountain and lake are natural images associated with the trigrams. They offer a way into the texts, not a scientific prediction of events.'],question:'How would you explain yin and yang lines to a friend?'},
{id:'reading',tag:'Read together · 2 min',title:'Learning from the movement of heaven',symbol:'䷀',intro:'A familiar idea becomes richer when we return to its source.',quote:'Heaven moves with strength; the exemplary person therefore strives without ceasing.',source:'Editorial English rendering from the Image commentary on Qian, Book of Changes',url:'https://ctext.org/text.pl?if=en&node=25011&remap=gb&show=parallel',paragraphs:['This passage draws on the movement of heaven to describe sustained personal effort. When reading a traditional text, distinguish its words from commentary and your own experience.','A modern reflection: ongoing learning can mean reading a short passage or writing down one question each day. This is our editorial reflection, not a word-for-word translation of the source.','When sharing, make clear what the source says and how you understand it. This gives others something to respond to and leaves room for different interpretations.'],question:'What small habit could keep your cultural learning alive?'},
{id:'sharing',tag:'Practice · 3 min',title:'Share a memory from home',symbol:'⌁',intro:'Culture lives in stories, festivals, everyday language and practical skills.',quote:'',source:'Original guide: recording and sharing cultural memories',url:'',paragraphs:['Choose a specific memory: how your family celebrates a festival, how a dialect expression is used, or a skill someone taught you. Concrete details are more useful than saying everyone does the same thing.','Record the place, time and your connection to the storyteller. Ask permission before sharing another person’s story. One family’s practice need not represent an entire region.','Ask how things differ elsewhere. When someone adds or corrects a detail, make room for multiple accounts and sources. Passing culture on includes listening, checking and continuing the conversation.'],question:'Which local tradition or expression would you record?'}
];
const QUIZ=[
{question:'Where do you start counting the six lines?',options:['At the bottom','At the top','In the middle'],answer:0,explanation:'Lines are counted from bottom to top. The lowest is the first line; the highest is the sixth.',lesson:'symbols'},
{question:'How many combinations can three yin or yang lines make?',options:['Six','Eight','Sixty-four'],answer:1,explanation:'Each line has two forms, so three lines give 2 × 2 × 2 = 8 combinations.',lesson:'symbols'},
{question:'How should the passage about heaven and ongoing effort be credited?',options:['As an anonymous internet saying','As my own writing','To the Image commentary on Qian'],answer:2,explanation:'Identify the original source and label your modern reflection separately. This helps others check and understand the passage.',lesson:'reading'},
{question:'Which approach works best when sharing a local custom?',options:['Describe my family’s practice and invite other experiences','Say everyone must celebrate this way','Say all different practices are wrong'],answer:0,explanation:'Separate personal memories from general claims and respect differences between families and regions.',lesson:'sharing'}
];
const TOPICS=[
{id:'memory',tag:'家乡记忆',title:'What local tradition would you like to pass on?',body:'Start with a festival, a dialect expression or a family story. Add a place and source where possible, and welcome different experiences.'},
{id:'reading',tag:'经典共读',title:'One passage, different perspectives',body:'Share a passage and its source, then explain your understanding. Different readings can coexist while we look for evidence together.'},
{id:'question',tag:'知识问答',title:'What would you like to ask about coins and hexagrams?',body:'Start with line positions, symbols or the source of a text. Being clear about what you are unsure of is a good beginning.'}
];
